import type { Metadata } from "next";
import "./reset.css";
import Navigation from "./components/navigation";

export const metadata: Metadata = {
  title: "DotHog's Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
